

services:
  app:
    container_name: app
    image: 'eduardcavasi/centered_game:0.0.1'
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:postgresql://db:5432/centered",
              "spring.datasource.username" : "postgres",
              "spring.datasource.password" : "parola",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=parola
      - POSTGRES_DB=centered
    ports:
      - 5432:5432

